import { BRAND_NAME, BRAND_TAGLINE } from "@/lib/brand";
import type { PawpsNormalizedRow } from "@/lib/pricelist-normalize-types";

function formatMoney(n: number | null): string {
  if (n == null) return "—";
  return n.toLocaleString("en-PH", { maximumFractionDigits: 2 });
}

export function exportPricelistPdf(
  supplier: string,
  rows: PawpsNormalizedRow[],
): void {
  const date = new Date().toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const tableRows = rows
    .map(
      (r, i) => `
      <tr>
        <td>${i + 1}</td>
        <td>${escapeHtml(r.type)}</td>
        <td>${escapeHtml(r.item)}</td>
        <td>${escapeHtml(r.flavor ?? "—")}</td>
        <td>${escapeHtml(r.size ?? "—")}</td>
        <td class="num">${formatMoney(r.per_kg)}</td>
        <td class="num ws">${formatMoney(r.wholesale)}</td>
        <td class="num retail">${formatMoney(r.retail)}</td>
      </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(BRAND_NAME)} — ${escapeHtml(supplier)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; margin: 24px; color: #111; }
    .header { border-bottom: 3px solid #e8a44a; padding-bottom: 12px; margin-bottom: 20px; }
    .brand { font-size: 22px; font-weight: 700; color: #0f0f14; }
    .tagline { font-size: 12px; color: #666; margin-top: 2px; }
    .meta { font-size: 13px; margin-top: 8px; color: #333; }
    h2 { font-size: 16px; margin: 0 0 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 11px; }
    th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
    th { background: #13131f; color: #fff; }
    tr:nth-child(even) { background: #f8f8fa; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .ws { color: #1a7a4a; font-weight: 600; }
    .retail { color: #2a5a9a; }
    .footer { margin-top: 16px; font-size: 10px; color: #888; }
    @media print {
      body { margin: 12px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">${escapeHtml(BRAND_NAME)}</div>
    <div class="tagline">${escapeHtml(BRAND_TAGLINE)}</div>
    <div class="meta">Normalized pricelist · ${escapeHtml(supplier)} · ${escapeHtml(date)} · ${rows.length} items</div>
  </div>
  <h2>Catalog preview</h2>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Type</th>
        <th>Item</th>
        <th>Flavor</th>
        <th>Size</th>
        <th>Per kg</th>
        <th>Wholesale</th>
        <th>Retail</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p class="footer">Generated by Pawps PH Pricelist Normalizer — internal use</p>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (!w) {
    alert("Allow pop-ups to export PDF (print dialog).");
    return;
  }
  w.document.write(html);
  w.document.close();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
